// packages/08-component-react/src/Counter.tsx
import { useState } from 'react'

export function Counter({ initial = 0, onChange }: {
  initial?: number
  onChange?: (n: number) => void
}) {
  const [count, setCount] = useState(initial)

  const update = (n: number) => {
    setCount(n)
    onChange?.(n)
  }

  return (
    <div>
      <p>count: {count}</p>
      <button aria-label="+" onClick={() => update(count + 1)}>+</button>
      <button aria-label="-" onClick={() => update(count - 1)}>-</button>
    </div>
  )
}

// packages/07-component-vue/src/Counter.vue
<script setup lang="ts">
import { ref } from "vue";

const props = defineProps<{ initial?: number }>();
const emit = defineEmits<{ (e: "change", n: number): void }>();

const count = ref(props.initial ?? 0);

function inc() {
  count.value++;
  emit("change", count.value);
}

function dec() {
  count.value--;
  emit("change", count.value);
}
</script>

<template>
  <div>
    <p>count: {{ count }}</p>
    <button @click="inc" aria-label="+">+</button>
    <button @click="dec" aria-label="-">-</button>
  </div>
</template>
